#!/bin/bash

##########
# v0.4.0 #
##########

logger -t 50-l2tp-vpn -p user.info "[$(whoami)] start script 50-l2tp-vpn"

# params
use_tg="false"
bot_token="<TG_TOKEN>"
chat_id="<CHAT_ID>"
chat_ids=("<CHAT_IDs>")
r_gw="<IP_ADDRESS>"
nets=("<NETWORKS>")
link="<TYPE OF LINK [gre, ppp, eth, etc]>"

# init
notify_msg=()
msgs=([0]="[$(whoami)] tg notify is disabled" [1]="[$(whoami)] wrong parameter on \"string 10\"" [2]="[$(whoami)] tun_addr is empty" [3]="[$(whoami)] parameter to logger_sl was not passed" [4]="$(whoami) from $(hostname) on $(date) added routes to your AS" [5]="$(whoami) from $(hostname) on $(date) sent messsge:" [6]="routes NOT added to your AS")
tun_addr=$(ifconfig | grep -A1 "$link[[:digit:]+]" | grep 'destination ' | awk -v addr=$r_gw '{if ($NF == addr) print $NF}')

notify_tg () {
  for i in ${chat_ids[@]}; do
    curl -s -X POST https://api.telegram.org/bot$bot_token/sendMessage -d chat_id=$i -d text="${msgs[5]} %0A ${notify_msg[*]}"
  done
}
logger_sl () {
  if [ -z "$1" ] ; then
    logger -t 50-l2tp-vpn -p user.info "${msgs[3]}"
  else
    logger -t 50-l2tp-vpn -p user.info "${msgs[$1]}"
  fi
}

if [[ -z "$tun_addr" ]] ; then
  logger_sl 2
  notify_msg+=( "${msgs[6]} %0A" )
elif [[ $tun_addr == $r_gw ]] ; then
  n=0
  sleep 1
  for i in ${nets[@]}; do
    result=$(ip route add $i via $r_gw 2>&1)
    if [ $? -eq 0 ]; then
      logger -t 50-l2tp-vpn -p user.info "[$(whoami)] route to $i via $r_gw added"
      notify_msg[n]="route to $i via $r_gw added %0A"
    else
      err_code=$?
      err_msg=$result
      logger -t 50-l2tp-vpn -p user.info "[$(whoami)] route to $i via $r_gw not added - $err_msg [errore code: $err_code]"
      notify_msg[n]="route to $i via $r_gw not added - $err_msg [errore code: $err_code] %0A"
    fi
    ((n+=1))
  done
else
  logger -t 50-l2tp-vpn -p user.info "nothing"
  notify_msg="nothing"
fi

case $use_tg in
  true)
    notify_tg
    ;;
  false)
    logger_sl 0
    ;;
  *)
    logger_sl 1
    ;;
esac

logger -t 50-l2tp-vpn -p user.info "[$(whoami)] finished script 50-l2tp-vpn"

exit $?
